[build]
  # The directory where Netlify will run the build command
  base = "vaultshift"
  
  # The directory that contains the deploy-ready assets
  publish = "dist"
  
  # The command Netlify will run to build your site
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
